### ISSUE TITLE
[web] Uncaught TypeError: Cannot read properties of undefined (reading 'src__prism')

### ISSUE THREAD

**Issue by rootasjey** [chenzhiguang/flutter_prism#14]
Hi,
First of all, thanks for this package.
It seems that this repository [example](https://github.com/tagnote-app/flutter_prism/tree/main/example) does not work on web (chrome) due to a prism issue.

<details>
  <summary>Uncaught SyntaxError: Unexpected token 'false'</summary>
  
  ```bash
Uncaught caught SyntaxError: Unexpected token 'false'
  ```
</details>

<details>
  <summary>Uncaught TypeError: Cannot read properties of undefined (reading 'src__prism')</summary>
  
  ```bash
Uncaught TypeError: Cannot read properties of undefined (reading 'src__prism')
    at load__packages__flutter_prism__src__prism_dart (prism.dart.lib.js:16:67)
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at callGetModule (require.js:1203:63)
    at Object.completeLoad (require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (require.js:1717:29)
  ```
</details>

## Steps to reproduce:

* Clone this repository: `gh repo clone tagnote-app/markdown_viewer`
* Navigate to the example folder: `cd makdown_view/example`
* Run the example: `flutter run -d chrome`

## Configuration:

* Flutter 3.7.12
* Dart 2.19.2
* Device: web (chrome)

**Comment by chenzhiguang** [comment]
@rootasjey Hi! Thank you too,  I will check it later soon.
